import json, re, hashlib
from pathlib import Path

SRC=Path('/mnt/c/Users/USER/Downloads/CDR_System_IR_v3_consistent_story.bento.html')
OUT=Path('/mnt/c/Users/USER/Downloads/CDR_System_IR_v4_product_videos.bento.html')
LOCAL=Path('/home/termi/work/cdr-bento/CDR_System_IR_v4_product_videos.bento.html')
html=SRC.read_text(encoding='utf-8')
m=re.search(r'(<script type="application/bento\+json" id="bento-doc">)\s*(.*?)\s*(</script>)', html, re.S)
if not m: raise SystemExit('missing bento doc')
doc=json.loads(m.group(2))
W,H=1280,720
BG='#111827'; FG='#F9FAFB'; MUTED='#D1D5DB'; MUTED2='#9CA3AF'; ACC='#2DD4BF'; BLUE='#60A5FA'; AMBER='#FBBF24'; BORDER='rgba(255,255,255,0.16)'; SURF='rgba(255,255,255,0.058)'
FONT='Inter, Pretendard, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif'
VIDEOS={
 'rwrp':'https://oopy.lazyrockets.com/api/v2/notion/fileUrl?src=attachment%3Ac4bbfb2c-4cc8-45f7-863a-ad32012acad4%3ANew_Robot_-_ENCY_simul__CDR_real.mp4&blockId=31e2cc10-9e12-80c8-a57a-f59852ee3fb9#t=0.0001',
 'cdr':'https://oopy.lazyrockets.com/api/v2/notion/fileUrl?src=attachment%3Af760667d-82aa-4e7f-a725-d69197e1037d%3AEncyManagerGUI%EB%A1%9C_%EC%88%9C%EC%B0%A8%EC%A1%B0%EA%B0%81_%ED%85%8C%EC%8A%A4%ED%8A%B8_%EC%98%81%EC%83%81_260115.mp4&blockId=31e2cc10-9e12-8033-99a5-f6cb0d9c54c3#t=0.0001',
 'crc':'https://oopy.lazyrockets.com/api/v2/notion/fileUrl?src=attachment%3A368f787e-5d4f-4aab-9a86-d19917bec6f2%3ACRC_%EC%84%9C%EB%B9%992%EC%B0%A8_%ED%85%80%EB%B8%94%EB%9F%AC250807.mp4&blockId=31f2cc10-9e12-808a-8054-d47c0a6771de#t=0.0001',
 'csr':'https://oopy.lazyrockets.com/api/v2/notion/fileUrl?src=attachment%3A231166dd-91e9-426d-8f90-7fb6823bb686%3ACSR_%EB%8F%84%EC%8A%A8%ED%8A%B8%EB%AA%A8%EB%93%9C(%EC%98%A4%ED%8F%AC%EB%AF%B8%EC%88%A0%EA%B4%80).mp4&blockId=31f2cc10-9e12-80ac-b5c1-dfc5463db726#t=0.0001',
}

def txt(id,x,y,w,h,html,size=30,weight=700,color=FG,align='left',line=1.15):
 return {'id':id,'type':'text','x':x,'y':y,'w':w,'h':h,'rotation':0,'opacity':1,'html':html,'fontSize':size,'fontFamily':FONT,'fontWeight':weight,'color':color,'align':align,'valign':'top','lineHeight':line}
def rect(id,x,y,w,h,fill=SURF,stroke=BORDER,sw=1,r=22):
 return {'id':id,'type':'shape','shape':'rect','x':x,'y':y,'w':w,'h':h,'fill':fill,'stroke':stroke,'strokeWidth':sw,'radius':r,'rotation':0,'opacity':1}
def media(id,x,y,w,h,src):
 return {'id':id,'type':'media','kind':'video','src':src,'x':x,'y':y,'w':w,'h':h,'rotation':0,'opacity':1,'controls':True,'muted':True,'autoplay':False,'loop':False,'fit':'cover','radius':18}
def footer(n):
 return [txt(f'foot{n}',96,672,520,24,'CDR System · product videos v4',16,500,MUTED2), txt(f'pg{n}',1118,672,66,24,f'{n:02d}',16,700,MUTED2,'right')]
def product_video_card(prefix,x,y,title,label,color,url):
 return [rect(prefix+'card',x,y,518,190,'rgba(255,255,255,0.058)',color,1,24), media(prefix+'video',x+18,y+18,230,130,url), txt(prefix+'title',x+272,y+26,210,32,title,28,800,color), txt(prefix+'label',x+272,y+68,208,64,label,20,500,MUTED,line=1.25), txt(prefix+'hint',x+272,y+142,208,24,'클릭해서 재생',16,600,MUTED2)]

video_slide={'id':'s4b-product-videos','name':'Product Videos','background':BG,'transition':'morph','notes':'홈페이지 하위 제품 페이지의 원본 video URL을 Bento media 요소로 링크 삽입. RwRP 전용 페이지에는 video가 없어 CDR 페이지의 Sim2Real 검증 영상을 RwRP 관련 영상으로 매핑. 큰 MP4는 파일 크기 때문에 임베드하지 않고 외부 링크로 유지.','elements':[
 txt('k',96,58,600,32,'제품별 홈페이지 영상',22,800,ACC), txt('h',96,100,880,66,'각 제품은 실제 동작 영상으로 설명합니다',48,800),
 *product_video_card('rwrp',96,202,'RwRP','Sim2Real 검증 / ENCY simul & CDR real',ACC,VIDEOS['rwrp']),
 *product_video_card('cdr',666,202,'CDR','EncyManager GUI 순차 조각 테스트',BLUE,VIDEOS['cdr']),
 *product_video_card('crc',96,430,'CRC','Customized Robot Café 서빙 테스트',AMBER,VIDEOS['crc']),
 *product_video_card('csr',666,430,'CSR','Customized Service Robot 도슨트 모드',FG,VIDEOS['csr']),
 txt('note',96,622,1088,26,'영상은 Bento 파일에 직접 포함하지 않고 홈페이지 원본 MP4를 링크합니다. 오프라인 발표 시에는 별도 임베드/압축 버전 필요.',18,500,MUTED2,'center'),
]+footer(5)}
# insert after Portfolio (index after slide name Portfolio)
slides=doc['slides']
insert_at=4
for i,s in enumerate(slides):
 if s.get('name')=='Portfolio': insert_at=i+1
slides.insert(insert_at, video_slide)
# renumber footers/page numbers for all slides
for idx,sl in enumerate(slides, start=1):
 # update existing footer texts generated by earlier versions
 for el in sl.get('elements',[]):
  if el.get('type')=='text' and (el.get('id','').startswith('pg') or el.get('id','').startswith('page-')):
   el['html']=f'{idx:02d}'
  if el.get('type')=='text' and el.get('id','').startswith('foot'):
   el['html']='CDR System · product videos v4'
 sl['notes']=(sl.get('notes','')+'\nV4: product video links inserted; Adham UI tips preserved.').strip()

doc['title']='CDR System IR v4 — Product Videos'
doc['slides']=slides
doc.setdefault('metadata',{})['status']='draft-v4-product-videos'
doc['metadata']['latestChange']='Inserted one homepage video per product: RwRP, CDR, CRC, CSR. Videos are external linked media, not embedded, to keep deck size manageable.'
doc['metadata']['videoMap']=VIDEOS
raw=json.dumps(doc,ensure_ascii=False,separators=(',',':')).replace('<','\\u003c')
new_html=html[:m.start(1)]+m.group(1)+'\n'+raw+'\n'+m.group(3)+html[m.end(3):]
OUT.write_text(new_html,encoding='utf-8')
LOCAL.write_text(new_html,encoding='utf-8')
print('wrote', OUT)
print('local', LOCAL)
print('slides', len(slides), 'bytes', OUT.stat().st_size)
print('sha256', hashlib.sha256(OUT.read_bytes()).hexdigest())
